<?php
/**
 *
 * Copyright (c) 2021. - Eighty / 20 Results by Wicked Strong Chicks.
 * ALL RIGHTS RESERVED
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package E20R\Licensing\Exceptions\NoLicenseKeyFound
 */

namespace E20R\Licensing\Exceptions;

use Exception;

/**
 * Custom exception raised when unable to locate a license key
 */
class NoLicenseKeyFound extends Exception {
	/**
	 * Exception constructor
	 *
	 * @param string $license_key Key for the licensed product generated by the WooCommerce store
	 */
	public function __construct( $license_key ) {

		$message = sprintf(
			// translators: %s - The License Key supplied
			__( 'Error: The specified license key (%1$s) was not found!', 'e20r-Utilities-Licensing' ),
			$license_key
		);
		parent::__construct( $message );
	}
}
