version: "3.9"

services:
  wordpress:
    container_name: e20r-codecepiton-wordpress
    build:
      context: /Users/sjolshag/PhpStormProjects/Utilities/tests
      dockerfile: docker/Dockerfile
      args:
        WP_TAG: wordpress:${WP_RELEASE}
    restart: always
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_SKIP_INSTALL: 'yes'
    volumes:
      - ${PLUGIN_DIR}:/var/www/html/wp-content/plugins/${E20R_PLUGIN_NAME}
      - ${PMPRO_DIR}:/var/www/html/wp-content/plugins/paid-memberships-pro
      - ${SQL_BACKUP_FILE}/${E20R_PLUGIN_NAME}.sql:/docker-entrypoint-initdb.d/${E20R_PLUGIN_NAME}.sql
    depends_on:
      - "database"

  database:
    image: mariadb:latest
    container_name: mariadb_wordpress
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}

# volumes:
