name: Run Unit Tests when creating a PR

# Run Unit Test when new PR is created
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr_tests:
    strategy:
      matrix:
        php_version: [ 7.3, 7.4, 8.0 ]
    name: Pull Request related testing - PHP {{ matrix.php_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with Composer V2+
        uses: shivammathur/setup-php@v2
        with:
          php-version: "{{ matrix.php_version }}"
          extensions: mbstring, xdebug
          tools: composer:v2
          coverage: pcov
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/Utilities
      - name: Run Code Standard Tests
        run: make code-standard-test
      - name: Run PHP Stan Tests
        run: make phpstan-test
      - name: Run the unit tests with coverage
        run: make coverage
      - name: Run the WP unit tests
        run: make wp-unit-test

