name: Release to Eighty20Results.com

on:
  # Deploy when a new release is created
  release:
    # Only deploy when the admin creates/publishes/edits/pre-releases from GitHub
    types: [edited, published]

jobs:
  # To push the release (sources) to the Eighty20Results.com plugin store
  wordpress:
    name: Push plugin to eighty20results.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p 18765 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Build and test plugin
        run: make build
        env:
          E20R_DEPLOYMENT_SERVER: ${{ secrets.SSH_HOST }}
          E20R_PLUGIN_NAME: 00-e20r-utilities
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
