name: Test of "Release to Eighty20Results.com" workflows

on:
  push:
    branches:
      - test_workflow*
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the Eighty20Results.com plugin store
  wordpress:
    name: Push plugin to eighty20results.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p 18765 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Build and test plugin
        run: make build
        uses: eighty20results/Utilities@main
        env:
          E20R_PLUGIN_NAME: 00-e20r-utilities
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
