name: Test of "Release to Eighty20Results.com" workflows

on:
  push:
    branches:
      - test_workflow*
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the Eighty20Results.com plugin store
  test_workflow:
    name: Push plugin to eighty20results.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: eighty20results/Utilities
          ref: test_workflow
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H -p 18765 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Build and test plugin
        run: make build
        env:
          E20R_PLUGIN_NAME: 00-e20r-utilities
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          CONTAINER_ACCESS_TOKEN: ${{ secrets.CONTAINER_ACCESS_TOKEN }}
      - name: Deploy plugin to download server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "~/build/00-e20r-utilities/00-e20r-utilities-*.zip"
          target: ${{ secrets.DEPLOY_TO_DIR }}
          rm: true
        env:
          E20R_PLUGIN_NAME: 00-e20r-utilities
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          CONTAINER_ACCESS_TOKEN: ${{ secrets.CONTAINER_ACCESS_TOKEN }}
